当代码在解析和运行的过程中发生了错误，就被称为异常。
错误
一个被用来描述错误的对象，当代码解析或运行出错时会被创建并抛出。JS 中原生提供一个 Error 构造函数，所有错误对象都是该构造函数的实例。
Error 的 prototype 对象上一般具有3个属性：
● message：错误提示信息
● name：错误类型的名称，默认为错误对象的构造函数的名字
● stack：错误产生时的堆栈信息，该属性为非标准属性
错误种类
Error 构造函数是 JS 中最基础的错误构造函数，除此之外，JS 还定义了其他6种类型的错误构造函数，它们都继承自 Error。分别是：
1. SyntaxError
在代码解析阶段，如果发现语法错误，就会生成该类型的对象，并抛出。
2. ReferenceError
当引用一个不存在或无法引用的变量时，就会生成该类型的对象，并抛出。
3. RangeError
当一个特定类型的值超出其限定范围或集合时，就会生成该类型的对象，并抛出。
4. TypeError
当一个值非预期类型时，就会生成该类型的对象，并抛出。
5. URIError
以一种错误的方式使用全局 URI 处理函数时，就会生成该类型的对象，并抛出。
6. EvalError
执行 eval() 函数时发生的错误。

根据 Error 错误基类与其派生类之间的原型关系，我们可以在 JS 提供的原生错误构造函数外，自定义错误类型，如：

function SelfError(message) {
  const inst = new Error(message);
  
  Object.setPrototypeOf(instance, SelfError.prototype);
  if (Error.captureStackTrace) {
    Error.captureStackTrace(instance, SelfError);
  }
  return inst;
}

Object.setPrototypeOf(SelfError.prototype, Error.prototype);
Object.setPrototypeOf(SelfError, Error);
SelfError.prototype.name = 'SelfError';
这样我们就自定义了一个错误类型了
异常来源
产生异常的场景非常多，常见的大致有以下几种：
● 代码语法错误，执行出错
● throw 语句：主动生成异常
● Promise 异常
● 静态资源加载异常
● 接口请求异常
● ....

异常捕获
所谓异常捕获，即获取异常所对应的错误信息。捕获异常的方法比较多，但每种方法都有其局限性，我们通常需要根据场景来选择不同的方法。
Try-catch
try-catch 语句是 JS 中异常捕获及处理的一种标准方式，通常被用来处理可预见的错误。
try {
  // 可能会产生错误的代码
} catch (error) {
  // 在错误发生时怎么处理
}
如果 try 块中的任何代码发生了错误，就会立即退出代码执行过程，然后执行 catch 块。
需要特别注意的是，try 块中异步代码产生的错误捕获不到，只有同步代码产生的错误才会被捕获。

window.error
window.onerror 主要被用来捕获代码运行时中哪些没有被捕获的、预料之外的错误。
需要注意的是，window.onerror 无法捕获 Promise 中抛出的异常和静态资源加载异常。
// 与其他 Element 上的 error 事件处理器函数不同，window 接收的是5个与 error 事件对象相关的参数，而不是单个 error 事件对象。
// 并且，和其他事件不同，error 事件可以通过处理器函数的返回值来取消事件，返回 true 即表示取消事件，这样错误就不会在控制台出现（这可能与无法获取到事件对象有关）
// https://developer.mozilla.org/en-US/docs/Web/API/Window/error_event
window.onerror = (message, source, lineno, colno, errorObj) => {
  console.log('捕获到异常：', { message, source, lineno, colno, errorObj });
  return true;
}

setTimeout(() => {
  console.log(ss);
}, 1000)


Promise 异常捕获
Promise 中抛出的错误无法被 onerror 或 try-catch 捕获到，我们通常使用 promise catch 方法来处理 promise 异常，对于没有被 catch 处理的异常，可以在全局增加一个 unhandledrejection 事件监听器来捕获遗漏掉的 promise 异常。
window.addEventListener("unhandledrejection", (e) => {
  e.preventDefault();
  console.log('捕获到异常：', e);
});

new Promise((resolve, reject) => {
  throw new Error('promise 异常');
}).catch((err) => {
  console.log('捕获到异常：', err);
});


静态资源加载异常
对于静态资源加载异常，我们通常有两种方式，一种是直接在静态资源标签上添加 onerror 方法。
<script>
  function errorHandler(ele) {
    console.log("捕获到静态资源加载异常", ele);
  }
</script>
<script src="http://xxx/test.js" onerror="errorHandler(this)"></script>
<link rel="stylesheet" href="http://xxx/test.css" onerror="errorHandler(this)">
一种是在全局添加异常监听器，因为网络请求异常事件不会事件冒泡，因此如果要捕获这类异常事件，需要在事件捕获阶段将其捕获。(注：这类错误事件无法被取消)。
// 该 error 监听器只会在事件捕获阶段触发
window.addEventListener('error', (error) => {
  console.log('捕获到异常：', error);
}, true);


接口请求异常
接口请求异常，一般是根据所使用的 HTTP 库来制定不同的策略。以常用的 HTTP 请求库 axios 为例，可通过其拦截器对请求异常进行监控处理。
// Add a response interceptor
axios.interceptors.response.use(function (response) {
    // Any status code that lie within the range of 2xx cause this function to trigger
    // Do something with response data
    return response;
  }, function (error) {
    // Any status codes that falls outside the range of 2xx cause this function to trigger
    if (error.response.status === 400) {
      // ...
    } else if (error.response.status === 502) {
      // ...
    }
    return Promise.reject(error);
  });

用处
● 了解 JS 的错误机制，提高错误处理的意识，增强代码质量。
● 便于搭建错误监控系统。
● 创建自己的函数库或组件库时，合理利用 Error 机制，让使用者能够清晰的了解使用时的错误。
